# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "980140d0a97687e598f1e1c03cae27af"
name = "polychrome-bagels"
handle = "polychrome-bagels"
application_url = "https://gorgeous-torrone-d73d15.netlify.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files,write_products"

[auth]
redirect_urls = ["https://gorgeous-torrone-d73d15.netlify.app/auth/callback", "https://gorgeous-torrone-d73d15.netlify.app/auth/shopify/callback", "https://gorgeous-torrone-d73d15.netlify.app/api/auth/callback"]

[pos]
embedded = false
